name: status
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  intl:
  flutter_staggered_animations: ^1.1.1
  pinput: ^5.0.0
  percent_indicator: ^4.2.3
  country_code_picker: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flame_splash_screen: ^0.3.0


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
