// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfT7ZCyPvDCw_hcVpbX02Hm8UYPlX4a7M',
    appId: '1:521259377830:web:5aee2aa667ef5a1f69c067',
    messagingSenderId: '521259377830',
    projectId: 'status-834e2',
    authDomain: 'status-834e2.firebaseapp.com',
    storageBucket: 'status-834e2.firebasestorage.app',
    measurementId: 'G-HTBD03J7PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYezY76V5v7yPLQ_1cj__nIDwGgloROCw',
    appId: '1:521259377830:android:329fb27c6750505169c067',
    messagingSenderId: '521259377830',
    projectId: 'status-834e2',
    storageBucket: 'status-834e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLBpz91BCyQRO2KP401CcZxH0dozPp68Q',
    appId: '1:521259377830:ios:6227e24dcacdde4069c067',
    messagingSenderId: '521259377830',
    projectId: 'status-834e2',
    storageBucket: 'status-834e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSocialPollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLBpz91BCyQRO2KP401CcZxH0dozPp68Q',
    appId: '1:521259377830:ios:6227e24dcacdde4069c067',
    messagingSenderId: '521259377830',
    projectId: 'status-834e2',
    storageBucket: 'status-834e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterSocialPollApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfT7ZCyPvDCw_hcVpbX02Hm8UYPlX4a7M',
    appId: '1:521259377830:web:41100a97e99c165d69c067',
    messagingSenderId: '521259377830',
    projectId: 'status-834e2',
    authDomain: 'status-834e2.firebaseapp.com',
    storageBucket: 'status-834e2.firebasestorage.app',
    measurementId: 'G-K0JHCJ0T5M',
  );
}
